#1 [WIP] OAuth Service Draft
k8s-community/k8s-community pull request #3
Opened 2017-05-15 05:35 UTC by rumyantseva

2017-05-15 14:39 UTC, takama requested changes
Looks good to me, except of commands for running the service.

2017-05-15 14:39 UTC, takama commented on .gitignore
> +templates
EOL

2017-05-15 14:39 UTC, takama commented on README.md
> +For example, you can run service using `go run` (not for production, only for experiment!):
Maybe we should do it via `make run` command?

2017-05-15 14:39 UTC, takama commented on README.md
> +
The same case. Can we hide all that in `Makefile`?

2017-05-15 20:30 UTC, vsaveliev commented
Please read https://github.com/k8s-community/github-integration/issues/2 - maybe we need to move this functionality in github-integration. Lets discuss it.

2017-05-16 07:22 UTC, rumyantseva commented on README.md
> +For example, you can run service using `go run` (not for production, only for experiment!):
fixed

2017-05-16 07:23 UTC, rumyantseva commented on README.md
> +
I don't think that hiding is a pretty good idea... Don't you mention `Dockerfile` instead of `Makefile`, do you?

2017-05-16 07:54 UTC, rumyantseva commented on .gitignore
> +templates
fixed

2017-05-16 07:55 UTC, takama approved these changes

2017-05-16 08:01 UTC, takama commented on README.md
> +
I mentioned `Makefile` which used as quick helper for running some complex command line tasks. The task above looks like complex command with a lot of parameters.

2017-05-16 08:03 UTC, rumyantseva commented on README.md
> +
Ok, I got it! Agreed.

2017-05-16 08:04 UTC, merged